import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { GiStairsGoal } from "react-icons/gi";
import { VscChecklist } from "react-icons/vsc";
import { RiMoneyDollarCircleFill } from "react-icons/ri";
import Header from "~/components/Header";
import FullScreenWrapper from "~/components/wrappers/FullScreenWrapper";

import { api } from "~/utils/api";
import { IUserProps } from "~/utils/types";
import { parseCookies } from "nookies";
import LoadingPage from "~/components/utils/LoadingPage";
const Home: NextPage = () => {
  var { userId } = parseCookies(null);
  if (!userId) return <LoadingPage />;
  else {
    return (
      <>
        <Head>
          <title>OrganizeMe</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <FullScreenWrapper>
          <Header />
          <div className="flex grow flex-col items-center justify-center gap-3 bg-[#f8f9fa] p-6 lg:flex-row">
            <div className="flex h-[300px] w-full  flex-col items-center justify-center rounded-md border border-gray-200 bg-green-500 shadow-sm lg:h-[500px] lg:w-1/3">
              <Link
                href={"/finances"}
                className="flex h-full w-full grow flex-col items-center justify-center"
              >
                <RiMoneyDollarCircleFill
                  style={{ color: "white", fontSize: "65px" }}
                />
                <p className="text-xl font-medium text-white">FINANÇAS</p>
                <p className="w-[60%] text-center text-white">
                  Acompanhe suas finanças pessoais e tenha controle do seu
                  orçamento.
                </p>
              </Link>
            </div>
            <div className="flex h-[300px] w-full flex-col items-center justify-center rounded-md border border-gray-200 bg-[#70d6ff] text-white shadow-sm lg:h-[500px] lg:w-1/3">
              <GiStairsGoal style={{ color: "white", fontSize: "65px" }} />
              <p className="mt-1 text-xl font-medium text-white">
                HÁBITOS E METAS
              </p>
              <p className="w-[60%] text-center text-white">Em construção...</p>
            </div>
            <div className="flex h-[300px] w-full flex-col items-center justify-center rounded-md border border-gray-200 bg-yellow-500 text-white shadow-sm lg:h-[500px] lg:w-1/3">
              <Link
                href={"/activities"}
                className="flex h-full w-full grow flex-col items-center justify-center"
              >
                <VscChecklist style={{ color: "white", fontSize: "65px" }} />
                <p className="mt-1 text-xl font-medium text-white">
                  ATIVIDADES A FAZER
                </p>
                <p className="w-[60%] text-center text-white">
                  Em construção...
                </p>
              </Link>
            </div>
          </div>
        </FullScreenWrapper>
      </>
    );
  }
};

export default Home;
