import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "~/components/Header";
import FullScreenWrapper from "~/components/wrappers/FullScreenWrapper";

import { api } from "~/utils/api";
import { IUserProps } from "~/utils/types";
const Home: NextPage = ({ user }: IUserProps) => {
  console.log("USER", user);
  return (
    <>
      <Head>
        <title>OrganizeMe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FullScreenWrapper>
        <Header />
        <div className="flex grow items-center justify-center gap-3 p-6">
          <div className="flex h-[500px] w-[40%] items-center justify-center border border-gray-200 shadow-sm">
            <Link href={"/finances"}>CONTROLE FINANCEIRO</Link>
          </div>

          <div className="flex h-[500px] w-[40%] items-center justify-center border border-gray-200 shadow-sm">
            HÁBITOS E METAS
          </div>
          <div className="flex h-[500px] w-[40%] items-center justify-center border border-gray-200 shadow-sm">
            ATIVIDADES A FAZER
          </div>
        </div>
      </FullScreenWrapper>
    </>
  );
};

export default Home;
